# Access point del Raspberry: lo smartphone si collega a questa rete.
interface=wlan0
driver=nl80211
ssid=GNOCCO
hw_mode=g
channel=7
country_code=IT
wmm_enabled=0
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
# CAMBIA QUESTA PASSWORD (minimo 8 caratteri)
wpa_passphrase=gnocco2026
